services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install --upgrade pip
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug --reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free