services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r ../requirements.txt
    startCommand: "cd /opt/render/project/src/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: LEAGUE_ID
        value: 738279
      - key: PORT
        fromService:
          type: web
          name: fpl-league-hub-api
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free