services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      echo "Current directory:" &&
      pwd &&
      echo "Directory contents:" &&
      ls -la &&
      python test_setup.py &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      PYTHONPATH=/opt/render/project/src/backend gunicorn \
        --workers=1 \
        --worker-class=uvicorn.workers.UvicornWorker \
        --bind=0.0.0.0:$PORT \
        --log-level=debug \
        wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: LOG_LEVEL
        value: debug
      - key: PORT
        value: 10000

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free