services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r ../requirements.txt
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://fpl_user:${POSTGRES_PASSWORD}@postgresql.render.com/fpl_league_hub
      - key: PORT
        value: 10000
      - key: LEAGUE_ID
        value: 738279
      - key: PYTHONPATH
        value: .

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free