services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      cd /opt/render/project/src/backend &&
      PYTHONPATH=/opt/render/project/src/backend gunicorn \
        --workers=1 \
        --worker-class=uvicorn.workers.UvicornWorker \
        --bind=0.0.0.0:$PORT \
        --log-level=debug \
        --timeout=120 \
        wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: LOG_LEVEL
        value: debug
      - key: DB_USER
        value: fpl_user
      - key: DB_NAME
        value: fpl_league_hub
      - key: LEAGUE_ID  # Adding this from your local env
        value: "738279"
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free