services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend  # This tells Render to look in the backend directory
    buildCommand: pip install -r requirements.txt  # Now it will look in backend/requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: LOG_LEVEL
        value: debug
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free