services:
  - type: web
    name: fpl-league-hub-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: chmod +x backend/start.sh && cd backend && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free