services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      chmod +x run.sh
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: PYTHONPATH=$PYTHONPATH:./app uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: ./app
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free