services:
  - type: web
    name: fpl-league-hub-api
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: LOG_LEVEL
        value: debug
      - key: DATABASE_URL
        fromDatabase:
          name: fpl_league_db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: fpl_league_db
    databaseName: fpl_league_hub
    user: fpl_user
    plan: free